no-perm: '&cУ вас нет прав на данное действие'
reload: '&aКонфигурация перезагружена.'
no-player: '&cВы не ввели игрока!'

help-message:
  - 'Помощь по использованию команд плагина'
  - '&6/tblacknick set (ник) - &aУстановить &fигроку &0Чёрный ник'
  - '&6/tblacknick remove (ник) - &cУдалить &fигроку &0Чёрный ник'
  - '&6/tblacknick reload - Перезагрузить конфиг'
on-blacknick:
  hp: 5
  who: 'Игрок {player} выдал чёрный ник игроку {target}.'
  title: 'На вас наложили &0ЧЁРНЫЙ НИК'
  subtitle: 'Теперь ваши права ограничены'
  message:
    - 'На вас наложили чёрный ник'
    - 'Вы имеете 4 хп'
    - 'Имеете ограниченное количество прав'
off-blacknick:
  title: 'С вас сняли &0ЧЁРНЫЙ НИК'
  subtitle: 'Теперь вы свободны'
  message:
    - 'Не нарушайте!'
have-blacknick: '&cДанный игрок уже имеет чёрный ник'
not-have-blacknick: 'У данного игрока нету чёрного ника'
effect-on-give: #Эффект и уровень эффекта
  - BLINDNESS;0
  - WEAKNESS;0
